name: browsing
description: browsings proxy
author: bbo
version: "0.1"

stages:
  martianProxy:
    plugin: martianProxy
    config:
      cert: "../../certs/cert.pem"
      key: "../../certs/key.pem"
      modifier:
        url.RegexFilter:
          regex: http(s|):\/\/(.*\.|){{ .target }}\/
          modifier:
            output:
          scope:
            - request
            - response
  output:
    parents:
     - martianProxy
    include: ./templates/helper/output.yml
    variables:
      raw_output:
        filepath: ./proxy.txt
      output:
        pattern: {{`"{{ .request.url }}"`}}
        filepath: ./proxy_urls.txt
