name: katana
description: katana
author: bbo
version: "0.1"

stages:
  katana:
    plugin: katana
  output:
    parents:
      - katana
    include: ./templates/helper/output.yml
    variables:
      raw_output:
        filepath: ./raw_katana.txt
      output:
        filepath: ./katana_url.txt
        pattern: {{`"{{ .request.method }} {{ .request.endpoint }} {{ .response.status_code }}"`}}
  stdoutput:
    plugin: output
    parents:
      - output
