name: recon
description: target recon
author: bbo
version: "0.1"
stages:
  shodanx:
    include: ./templates/recon/shodanx.yml
  subfinder:
    include: ./templates/recon/subfinder.yml

  urls:
    include: ./templates/helper/output.yml
    variables:
      raw_output:
        filepath: ./recon_aggregated_results.txt
    parents:
      - subfinder
      - shodanx
