name: shodanx
description: search subdomain using shodanx
author: bbo
version: "0.1"
stages:
  shodanx:
    plugin: pipe
    config:
      - goTemplate:
          format: string
          pattern: {{`" subdomain -d {{ . }}" `}}
      - docker:
          image: shodanx:latest
  output:
    parents:
      - shodanx
    include: ./templates/helper/output.yml
    variables:
      raw_output:
        filepath: ./raw_shodanx.txt
