name: subfinder
description: search dubdomain using subfinder
author: bbo
version: "0.1"
stages:
  prepareSubfinder:
    plugin: transform
    config:
      - goTemplate:
          format: string
          pattern: " -d {{ . }} -silent -rl 10 -oJ"
  subfinder:
    parents:
      - prepareSubfinder
    plugin: docker
    config:
      image: projectdiscovery/subfinder:latest
  output:
    parents:
      - subfinder
    include: ./templates/helper/output.yml
    variables:
      raw_output:
        filepath: ./raw_subfinder.txt
