name: subfinder
description: search dubdomain using subfinder
author: bbo
version: "0.1"
stages:
  subfinder:
    plugin: pipe
    config:
      - goTemplate:
          format: string
          pattern: {{`" -d {{ . }} -silent -rl 10 -oJ"`}}
      - docker:
          image: projectdiscovery/subfinder:latest
  output:
    parents:
      - subfinder
    include: ./templates/helper/output.yml
    variables:
      raw_output:
        filepath: ./raw_subfinder.txt
      output:
        pattern: {{ "{{ .host }}" | quote }}
        format : json
        filepath: ./url_subfinder.txt
