name: sherlock
description: osint
author: bbo
version: "0.1"
stages:
  prepareSherlockCLI:
    plugin: transform
    config:
      - goTemplate:
          format: string
          pattern: " --no-color  {{ . }}"
  sherlock:
    parents:
      - prepareSherlockCLI
    plugin: docker
    config:
      image: sherlock/sherlock:latest
  enola:
    plugin: enola
  enolaOutput:
    parents:
      - enola
    plugin: transform
    config:
      - insert:
          content: "\n"
  output:
    parents:
      - sherlock
      - enolaOutput
    plugin: rawfile
    config:
      filepath: ./sherlock.txt
