name: blackbird
description: osint
author: bbo
version: "0.1"
stages:
  inputRaw:
    plugin: rawinput
    config:
      data: benji-bou
  blackbird:
    parents:
      - inputRaw
    plugin: docker
    pipe:
      - goTemplate:
          format: string
          pattern: --username {{ . }}
    config:
      image: blackbird:latest
  transformOutput:
    parents:
      - blackbird
    plugin: forward
    pipe:
      - split:
          sep: "\n"
        goTemplate:
          format: string
          pattern: "{{ trim . }}"
