name: test
description: osint
author: bbo
version: "0.1"
stages:
  generateHoleheCli:
    plugin: transform
    config:
      - goTemplate:
          format: string
          pattern: "holehe --only-used --no-color --no-clear {{ . }}"
  holehe:
    parents:
      - generateHoleheCli
    plugin: docker
    config:
      image: "holehe:latest"

  outputHolehe:
    parents:
      - holehe
    config:
      filepath: ./holehe_res.txt
    plugin: rawfile
