name: test
description: osint
author: bbo
version: "0.1"
stages: 
  inputName: 
    plugin: rawinput
    config: 
      data: "bouachour.benjamin@gmail.com"
  generateHoleheCli:
    parents: 
      - inputName
    plugin: transform
    config:
      - goTemplate:
          format: string
          pattern: "holehe --only-used --no-color --no-clear {{ . }}" 
  holehe:
    parents: 
      - generateHoleheCli
    plugin: docker
    config:
      host: unix:///Users/benjamin/.orbstack/run/docker.sock
      image: "holehe:latest"

  outputHolehe:
    parents: 
      - holehe
    plugin: output
