name: recon
description: target recon
author: bbo
version: "0.1"
stages:
  shodanx:
    include: ./templates/shodanx.yml
  subfinder:
    include: ./templates/subfinder.yml
  output:
    parents:
      - subfinder
      - shodanx
    plugin: stdoutput
  rawfile:
    plugin: rawfile
    parents:
      - subfinder
      - shodanx
    config:
      filepath: ./aggregate_results.txt
