name: test
description: osint
author: bbo
version: "0.1"
stages:
  prepareSubfinder:
    plugin: transform
    config:
      command: subfinder -d {{.}} -silent
  subfinder:
    plugin: docker
    config:
      image: projectdiscovery/subfinder:latest
  write:
    parents:
      - subfinder
    plugin: stdoutput
