name: test
description: test template
author: bbo
version: "0.1"

stages:
  martianProxy:
    plugin: martianProxy
    config:
      cert: "../../../../certs/cert.pem"
      key: "../../../../certs/key.pem"
      modifier:
        url.RegexFilter:
          regex: http(s|):\/\/(.*\.|)bioserenity\.cloud
          modifier:
            output:
          scope:
            - request
            - response
  extractRequestURL:
    parents:
      - martianProxy
    plugin: transform
    config:
     - goTemplate:
        format: json
        pattern: "{{ .request.url }}\n"
  distinctURL:
    parents:
      - extractRequestURL
    plugin: distinct
  martian_output:
    parents:
      - distinctURL
    config:
      filepath: ./martian_res.txt
    plugin: rawfile
