name: test
description: test template
author: bbo
version: "0.1"

stages:
  test:
    plugin: rawfile
    config:
      filepath: test.txt
  out:
    plugin: stdoutput
  trasform:
    plugin: transform
    config:
      - goTemplate:
          format: string
          pattern: "{{.}}"
